
route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'jessica_alarmes'
            channel: '#monitoamento'
            api_url: 'https://hooks.slack.com/services/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'
